GET http://localhost:5000/api/notification-groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODBjMzhmNi01ZmFlLTRmMzMtYTkwZS1mMDU2NWFhMTM3NjYiLCJnaXZlbl9uYW1lIjoiZG9jaGlodW5nMTAiLCJqdGkiOiJhNWU0YjE2Mi1mMzMwLTQ3ZDQtODY2NS01MTVhNmIxNWMxMWMiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE2ODUzMjIyMzgsImV4cCI6MTY4NTUzODIzOCwiaWF0IjoxNjg1MzIyMjM4LCJpc3MiOiJ5b3UtY2FuLWNhbGwtbWUtYmVzdC15aSIsImF1ZCI6IkF1dGggZUNvbW1lcmNlIn0.zwP45H6ZnphY6JczfyMP27jvWfFUxrLCLSc_zVpE3gs
