GET http://localhost:5000/api/notification-groups/6a39f6bc-939f-4e32-b445-9feeaddeb2c9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NzM1N2E2OC05ZGU4LTQwOTgtODAyZC1iYTRlOTI2ZGM1NGEiLCJnaXZlbl9uYW1lIjoiZG9jaGlodW5nMTExIiwianRpIjoiODllNGU3ZWUtZmQwYy00NjU4LWE4YzYtZGU1ZWM2MGY5ZGVmIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNjg1NjkyNzc5LCJleHAiOjE2ODU5MDg3NzksImlhdCI6MTY4NTY5Mjc3OSwiaXNzIjoieW91LWNhbi1jYWxsLW1lLWJlc3QteWkiLCJhdWQiOiJBdXRoIGVDb21tZXJjZSJ9.6kQBqvHn5xEtYpFAJ0OEhqCu0M4D4DaPwQRgUuPbec0
