GET http://localhost:5000/api/notification-groups/6a39f6bc-939f-4e32-b445-9feeaddeb2c9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OWZjNWFiNy1jNWI0LTRhY2QtYjU1Ny1hNGExYTkxOWVlMzUiLCJnaXZlbl9uYW1lIjoiZG9jaGlodW5nMTExIiwianRpIjoiMTBkZWRiOGQtYWY0OC00MzliLWFmZTgtNWJkOWU3NWJlMGE5Iiwicm9sZSI6IkFkbWluIiwibmJmIjoxNjg1OTMzMTQ4LCJleHAiOjE2ODYxNDkxNDgsImlhdCI6MTY4NTkzMzE0OCwiaXNzIjoieW91LWNhbi1jYWxsLW1lLWJlc3QteWkiLCJhdWQiOiJBdXRoIGVDb21tZXJjZSJ9.5ps5b2a1tuOMYg7PDpEc4DrRAveIpbMMmfyvKttnXXE
